jwt:
  jwt-key: "c7L0+z1bI67OpGIeYN9NcKgXBsHKiR2RlYX1Vzj4ULA="



spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/wanted?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:

  jpa:
#    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
